# Generated by Django 4.2.10 on 2024-07-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_project_status'),
        ('operation', '0007_remove_projectupdate_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='project_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='project.project'),
            preserve_default=False,
        ),
    ]
