# Generated by Django 4.2.10 on 2024-07-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_projectupdate_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectupdate',
            name='man_days_filled',
        ),
    ]
