# Generated by Django 4.2.10 on 2024-07-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_rename_project_projectassignment_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
