# Generated by Django 4.2.10 on 2024-07-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Project_Initiated', 'Project Initiated'), ('To_Be_Started', 'To Be Started'), ('In_Progress', 'In Progress'), ('Completed', 'Completed'), ('On_Hold', 'On Hold')], default='Project_Initiated', max_length=20),
        ),
    ]
